### ISSUE TITLE
Trabajos pendientes

### ISSUE THREAD

**Issue by ambarja** [barja8/IntroSQL#2]
@deygurc  por favor encargate de la **sesión 00** para instalar todo los softwares que se usaran en este pequeño curso pero en el sistema operativo de **windows** , has un pequeño manual en **markdown** algo parecido al que yo realicé en Linux.

**Comment by deygurc** [comment]
@barja8  Listo Barja yo me encargo de esa parte del trabajo pero necesito una guía para hacerlo..

**Comment by ambarja** [comment]
@deygurc  puedes guiarte de este primer avance solo dale click [aquÍ](https://github.com/barja8/IntroSQL/blob/master/Sesiones/0.%20Instalaci%C3%B3n%20de%20software%20-%20GNU_LINUX.md) y el manual puedes hacerlo algo paracido a este mira [aquÍ](https://github.com/pigreco/COVID19_Sicilia) más que nada la flecha que sea el mismo si puedes :nerd_face:
