### ISSUE TITLE
Agregar ejemplos reproducibles

### ISSUE THREAD

**Issue by ambarja** [barja8/IntroSQL#3]
Hola @bzdjahna estado revisando tu aporte y realmente déjame felicitarte, está super!, sin embargo para hacerlo más dinámico a las **sesiones** crees que puedes agregar algunos ejemplos reproducibles dando a conocer justamente estas funcionalidades de **SELECT**, por ejemplo puedes usar la información de [**REDATAM**](http://censos2017.inei.gob.pe/redatam/) y trabajarlo en **QGIS**  y luego ese proyecto los subes a la carpeta de [**Ejemplos**](https://github.com/barja8/IntroSQL/tree/master/Ejemplos), ojo es opcional, pero si tienes una idea igual me lo comentas :cat: :nerd_face:

**Comment by barja8** [comment]
dvvdvndcndsdcdndcvddvsdd

**Comment by bzdjahna** [comment]
Hola @barja8 ! ! !
Pude corregir y mejorar la primera versión del tema sobre consultas SELECT. Utilizando información proveniente de la base de datos Redatam, específicamente sobre población (censo 2017), mostrados gráficamente en Qgis < 3. Así que, ahí va! jaja. Gracias por las recomendaciones. = D
