### ISSUE TITLE
New contributor 

### ISSUE THREAD

**Issue by ambarja** [barja8/IntroSQL#6]
@bzdjahna  today is an special day because @MelvinREGeo8  is the new contributor on this project of SQL4Geographer :cat:,
finally I want to make some recomentation about **PostGIS** and **PgAdmin** I think that we should use the **GDAL** recently version (3.x) because it has new thing how for example **Geopdf**, please @MelvinREGeo8  if you can research about this, it will be nice work.

**Comment by bzdjahna** [comment]
@barja8 @MelvinREGeo8 Hi everyone! and a warm welcome to our new partner Melvin. GDAL sounds interesting.
I will continue with tables with spatial data, while Melvin looks for information about GDAL.
